---
title: "Lab2_Task13"
author: "Viktor Ushkov"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

### Задание 13

Используйте файл Air_flows.txt

Напишите функцию, которая создает именованный список, в котором имена - это названия городов, значения -- общее количество пассажиров прибывших в города. Напишите функцию, которая по названию города выводит список тех городов, в которые осуществляются перевозки из этого города.

```{r warning=FALSE}
# в условии к заданию был указан .txt файл, но был выложен .xlsx файл - подгрузим библиотеку для чтения xlsx файлов, в самих функциях будут использованы только базовые методы R
library(xlsx)
# загружаем таблицу, указываем StartRow и EndRow, чтобы избавиться от лишних заголовков в начале и источника информации в конце документа
df <- read.xlsx(file="data/air_flows.xlsx", 1, startRow = 6, endRow = 186)
# следующая строчка нужна, чтобы поправить названия столбцов для годов - при чтении таблицы они считались как "X2000", "X2005", "X2006"
colnames(df) <- c("Город1", "Город2", "2000", "2005", "2006")

# функция, которая создает именованный список, в котором имена - это названия городов, значения – общее количество пассажиров прибывших в города
num_of_passengers <- function(DF) {
  # вектор с уникальными значениями городов из таблицы
  cities <- unique(DF[, "Город2"])
  
  # функция, считающая количество пассажиров прибывших в    один город за 2000, 2005 и 2006 годы
  get_sum_of_passengers <- function(city) {
    sum(df[df$Город2 == city, c("2000", "2005", "2006")])
  }
  
  # с помощью lapply применяем функцию выше на все города
  res_list <- lapply(as.list(cities), get_sum_of_passengers)
  # подставляем названия городов в имена списка
  names(res_list) <- cities
  return(res_list)
}

# функция, которая по названию города выводит список тех городов, в которые осуществляются перевозки из этого города.
available_flights <- function(city) {
  # выбираем необходимые значения и представляем в виде списка
  cities_list <- as.list(df[df$Город1 == city, "Город2"])
  print(cities_list)
}
```

Примеры работы функций

```{r warning=FALSE}
# список с количеством прибывших в города пассажиров (в тыс. человек)
list_of_passengers_number <- num_of_passengers(df)
print(list_of_passengers_number)
```

```{r warning=FALSE}
#куда осуществляются перевозки из Архангельска
available_flights("Архангельск")
```

```{r warning=FALSE}
#куда осуществляются перевозки из Санкт-Петербурга
available_flights("Санкт-Петербург")
```

```{r warning=FALSE}
#куда осуществляются перевозки из Владивостока
available_flights("Владивосток")
```
